apiVersion: v1
kind: Pod
metadata:
  annotations:
  labels:
    name: expose
  name: test
  namespace: playground
spec:
  subdomain: subdomain
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: worker.gardener.cloud/pool
            operator: In
            values:
            - worker-opt
  containers:
  - args:
    - proxy
    - sidecar
    - --domain
    - $(POD_NAMESPACE).svc.cluster.local
    - --proxyLogLevel=warning
    - --proxyComponentLogLevel=misc:error
    - --log_output_level=default:info
    - --concurrency
    - "2"
    env:
    - name: JWT_POLICY
      value: third-party-jwt
    - name: PILOT_CERT_PROVIDER
      value: istiod
    - name: CA_ADDR
      value: istiod-1-11-4.istio-system.svc:15012
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: INSTANCE_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: SERVICE_ACCOUNT
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.serviceAccountName
    - name: HOST_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: PROXY_CONFIG
      value: |
        {"discoveryAddress":"istiod-1-11-4.istio-system.svc:15012","envoyAccessLogService":{"address":"enterprise-agent.gloo-mesh:9977"},"envoyMetricsService":{"address":"enterprise-agent.gloo-mesh:9977"},"proxyMetadata":{"GLOO_MESH_CLUSTER_NAME":"playground","ISTIO_META_DNS_AUTO_ALLOCATE":"true","ISTIO_META_DNS_CAPTURE":"true"}}
    - name: ISTIO_META_POD_PORTS
      value: |-
        [
            {"name":"http","containerPort":8080,"protocol":"TCP"}
            ,{"name":"status","containerPort":5747,"protocol":"TCP"}
        ]
    - name: ISTIO_META_APP_CONTAINERS
      value: worker
    - name: ISTIO_META_INTERCEPTION_MODE
      value: REDIRECT
    - name: ISTIO_META_WORKLOAD_NAME
      value: worker-l-cc9sc
    - name: ISTIO_META_OWNER
      value: kubernetes://apis/batch/v1/namespaces/playground/jobs/worker-l-cc9sc
    - name: ISTIO_META_MESH_ID
      value: playground.solo.io
    - name: TRUST_DOMAIN
      value: playground.solo.io
    - name: GLOO_MESH_CLUSTER_NAME
      value: playground
    - name: ISTIO_META_DNS_AUTO_ALLOCATE
      value: "true"
    - name: ISTIO_META_DNS_CAPTURE
      value: "true"
    - name: ISTIO_META_CLUSTER_ID
      value: playground
    - name: ISTIO_META_NETWORK
      value: playground-network
    image: scmoptimization.common.repositories.cloud.sap/istio-enterprise/proxyv2:1.11.4-solo-fips
    imagePullPolicy: IfNotPresent
    lifecycle:
      preStop:
        exec:
          command:
          - /bin/sh
          - -c
          - while [ $(netstat -plunt | grep tcp | grep -v envoy | wc -l | xargs) -ne
            0 ]; do sleep 1; done
    name: istio-proxy
    ports:
    - containerPort: 15090
      name: http-envoy-prom
      protocol: TCP
    readinessProbe:
      failureThreshold: 30
      httpGet:
        path: /healthz/ready
        port: 15021
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 2
      successThreshold: 1
      timeoutSeconds: 3
    resources:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 250Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 1337
      runAsNonRoot: true
      runAsUser: 1337
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/istio
      name: istiod-ca-cert
    - mountPath: /var/lib/istio/data
      name: istio-data
    - mountPath: /etc/istio/proxy
      name: istio-envoy
    - mountPath: /var/run/secrets/tokens
      name: istio-token
    - mountPath: /etc/istio/pod
      name: istio-podinfo
  - env:
    - name: UAA_CUSTOMSERVICEINSTANCEID
      value: dev
    - name: K8S_CLUSTERID
      value: playground
    - name: STORAGE_TYPE
      value: azure-blobstorage
    - name: STORAGE_BLOBSTORAGE_ACCOUNTNAME
      valueFrom:
        secretKeyRef:
          key: STORAGE_BLOBSTORAGE_ACCOUNTNAME
          name: o10n-storage-secret
    - name: STORAGE_BLOBSTORAGE_ACCOUNTKEY
      valueFrom:
        secretKeyRef:
          key: STORAGE_BLOBSTORAGE_ACCOUNTKEY
          name: o10n-storage-secret
    - name: JOBTAG_TAGSTORE_BLOBSTORAGE_ACCOUNTNAME
      valueFrom:
        secretKeyRef:
          key: JOBTAG_TAGSTORE_BLOBSTORAGE_ACCOUNTNAME
          name: o10n-jobtag-secret
    - name: JOBTAG_TAGSTORE_BLOBSTORAGE_ACCOUNTKEY
      valueFrom:
        secretKeyRef:
          key: JOBTAG_TAGSTORE_BLOBSTORAGE_ACCOUNTKEY
          name: o10n-jobtag-secret
    - name: QUEUE_REDIS_ADDR
      valueFrom:
        secretKeyRef:
          key: REDIS_ADDR
          name: o10n-redis-secret
    - name: QUEUE_REDIS_PW
      valueFrom:
        secretKeyRef:
          key: REDIS_PW
          name: o10n-redis-secret
    - name: WORKER_JOB_SIZE
      value: "2"
    - name: QUEUE_REDIS_DB
      valueFrom:
        secretKeyRef:
          key: REDIS_DB
          name: o10n-redis-secret
    - name: QUEUE_REDIS_CLUSTERMODE
      value: single
    - name: KUBERNETES_SERVICE_HOST
      value: api.playground.oaas-dev.internal.canary.k8s.ondemand.com
    image: scoptimizer.common.repositories.cloud.sap/scoptimizer/development/worker/adrian
    imagePullPolicy: Always
    name: worker
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    - containerPort: 5747
      name: status
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      failureThreshold: 3
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: "10"
        memory: 430Gi
      requests:
        cpu: "8"
        memory: 130Gi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/tmp/data
      name: o10n-worker-data
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: regcred
  initContainers:
  - args:
    - istio-iptables
    - -p
    - "15001"
    - -z
    - "15006"
    - -u
    - "1337"
    - -m
    - REDIRECT
    - -i
    - '*'
    - -x
    - ""
    - -b
    - '*'
    - -d
    - 15090,15021,15020
    env:
    - name: GLOO_MESH_CLUSTER_NAME
      value: playground
    - name: ISTIO_META_DNS_AUTO_ALLOCATE
      value: "true"
    - name: ISTIO_META_DNS_CAPTURE
      value: "true"
    image: scmoptimization.common.repositories.cloud.sap/istio-enterprise/proxyv2:1.11.4-solo-fips
    imagePullPolicy: IfNotPresent
    name: istio-init
    resources:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 250Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: false
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  nodeName: shoot--oaas-dev--playground-worker-opt-z2-6858f-bsh4v
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    runAsNonRoot: true
  serviceAccount: o10n-basic
  serviceAccountName: o10n-basic
  terminationGracePeriodSeconds: 259200
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir:
      medium: Memory
    name: istio-envoy
  - emptyDir: {}
    name: istio-data
  - downwardAPI:
      defaultMode: 420
      items:
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels
        path: labels
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.annotations
        path: annotations
    name: istio-podinfo
  - name: istio-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: istio-ca
          expirationSeconds: 43200
          path: istio-token
  - configMap:
      defaultMode: 420
      name: istio-ca-root-cert
    name: istiod-ca-cert
  - emptyDir: {}
    name: o10n-worker-data

