apiVersion: v1
kind: Pod
metadata:
  labels:
    job-name: ${PODNAME}
    name: expose
    scaledjob.keda.sh/name: o10n-worker-${JOBSIZE}
  name: m${PODNAME}
  namespace: playground
spec:
  nodeName: ${NODE}
  clonePod: ${PODNAME}
  containers:
  - env:
    - name: UAA_CUSTOMSERVICEINSTANCEID
      value: dev
    - name: K8S_CLUSTERID
      value: playground
    - name: STORAGE_TYPE
      value: azure-blobstorage
    - name: STORAGE_BLOBSTORAGE_ACCOUNTNAME
      valueFrom:
        secretKeyRef:
          key: STORAGE_BLOBSTORAGE_ACCOUNTNAME
          name: o10n-storage-secret
    - name: STORAGE_BLOBSTORAGE_ACCOUNTKEY
      valueFrom:
        secretKeyRef:
          key: STORAGE_BLOBSTORAGE_ACCOUNTKEY
          name: o10n-storage-secret
    - name: JOBTAG_TAGSTORE_BLOBSTORAGE_ACCOUNTNAME
      valueFrom:
        secretKeyRef:
          key: JOBTAG_TAGSTORE_BLOBSTORAGE_ACCOUNTNAME
          name: o10n-jobtag-secret
    - name: JOBTAG_TAGSTORE_BLOBSTORAGE_ACCOUNTKEY
      valueFrom:
        secretKeyRef:
          key: JOBTAG_TAGSTORE_BLOBSTORAGE_ACCOUNTKEY
          name: o10n-jobtag-secret
    - name: QUEUE_REDIS_ADDR
      valueFrom:
        secretKeyRef:
          key: REDIS_ADDR
          name: o10n-redis-secret
    - name: QUEUE_REDIS_PW
      valueFrom:
        secretKeyRef:
          key: REDIS_PW
          name: o10n-redis-secret
    - name: WORKER_JOB_SIZE
      value: "0"
    - name: QUEUE_REDIS_DB
      valueFrom:
        secretKeyRef:
          key: REDIS_DB
          name: o10n-redis-secret
    - name: QUEUE_REDIS_CLUSTERMODE
      value: single
    image: scoptimizer.common.repositories.cloud.sap/development/worker/adrian:latest
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 30
      httpGet:
        path: /health
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 50
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: worker
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    - containerPort: 5747
      name: status
      protocol: TCP
    resources:
      limits:
        cpu: "3"
        memory: 430Gi
      requests:
        cpu: "0.5"
        memory: 30Gi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
    startupProbe:
      failureThreshold: 50
      httpGet:
        path: /ready
        port: 8080
        scheme: HTTP
      periodSeconds: 3
      successThreshold: 1
      timeoutSeconds: 1
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/tmp/data
      name: o10n-worker-data
    - mountPath: /tmp
      name: o10n-worker-tmp
    - mountPath: /engines
      name: o10n-worker-engines
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: regcred
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    runAsNonRoot: true
  serviceAccount: o10n-basic
  serviceAccountName: o10n-basic
  subdomain: subdomain
  terminationGracePeriodSeconds: 259200
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - azureFile:
      secretName: azure-secret
      shareName: checkpoints
      readOnly: false
    name: o10n-worker-data
  - emptyDir:
      sizeLimit: 5Gi
    name: o10n-worker-tmp
  - emptyDir: {}
    name: o10n-worker-engines
